package com.umanteam.dadakar.admin.front;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DadakarFrontAdminApplication  {

	// public static String tokenValue = "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJmMmU3M2QyMy05NjEzLTRhZjgtOWY3MC1hNTE4YTExODk4OGUiLCJzdWIiOiJ1c2VyMSIsImlhdCI6MTUwNDg1NjI4MiwiZXhwIjozMDAxNTA0ODU2MjgyfQ.QQpHMpHkgjWMCjuC2cqkhaXyhwcTlWIoVtFcArHTJ-pzwb1V7bIKdhN4g2z_5IgWnxNvrxmT15CrovhyGMQH3Q";
	public static String tokenValue = "eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJlMDE0ZDlmMy1iZjYyLTRiNjQtOTI0Yi05MjczMjZhYWY2NWIiLCJzdWIiOiJ1c2VybmFtZTAiLCJpYXQiOjE1MDUxMjAwMTYsImV4cCI6MzAwMTUwNTEyMDAxNn0.6B3wWnwACayghH2ESCo4RYkwSlch3wELa6jxzbpCY175zbkMRMHPPShOX777IGYZkm3QH1k2mip0EgUs_ibwCw";
	
	public static void main(String[] args) {
		SpringApplication.run(DadakarFrontAdminApplication.class, args);
	}

}
